# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -march=v810 -global-isel -run-pass=legalizer %s -o - | FileCheck %s
---
name:              s16_sdiv
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s16_sdiv
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[SDIV:%[0-9]+]]:_(s32) = G_SDIV [[SEXT]], [[SEXT1]]
    ; CHECK-NEXT: $r10 = COPY [[SDIV]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_SDIV %1, %1
    %3:_(s32) = G_ANYEXT %2
    $r10 = COPY %3:_(s32)
    RET implicit $r10
...
---
name:              s16_udiv
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s16_udiv
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[UDIV:%[0-9]+]]:_(s32) = G_UDIV [[AND]], [[AND1]]
    ; CHECK-NEXT: $r10 = COPY [[UDIV]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_UDIV %1, %1
    %3:_(s32) = G_ANYEXT %2
    $r10 = COPY %3:_(s32)
    RET implicit $r10
...
---
name:              s16_srem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s16_srem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[SREM:%[0-9]+]]:_(s32) = G_SREM [[SEXT]], [[SEXT1]]
    ; CHECK-NEXT: $r10 = COPY [[SREM]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_SREM %1, %1
    %3:_(s32) = G_ANYEXT %2
    $r10 = COPY %3:_(s32)
    RET implicit $r10
...
---
name:              s16_urem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s16_urem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[UREM:%[0-9]+]]:_(s32) = G_UREM [[AND]], [[AND1]]
    ; CHECK-NEXT: $r10 = COPY [[UREM]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_UREM %1, %1
    %3:_(s32) = G_ANYEXT %2
    $r10 = COPY %3:_(s32)
    RET implicit $r10
...
---
name:              s16_sdivrem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s16_sdivrem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
    ; CHECK-NEXT: [[SDIVREM:%[0-9]+]]:_(s32), [[SDIVREM1:%[0-9]+]]:_ = G_SDIVREM [[SEXT]], [[SEXT1]]
    ; CHECK-NEXT: $r10 = COPY [[SDIVREM]](s32)
    ; CHECK-NEXT: $r11 = COPY [[SDIVREM1]](s32)
    ; CHECK-NEXT: RET implicit $r10, implicit $r11
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16), %3:_(s16) = G_SDIVREM %1, %1
    %4:_(s32) = G_ANYEXT %2
    %5:_(s32) = G_ANYEXT %3
    $r10 = COPY %4:_(s32)
    $r11 = COPY %5:_(s32)
    RET implicit $r10, implicit $r11
...
---
name:              s16_udivrem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s16_udivrem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[UDIVREM:%[0-9]+]]:_(s32), [[UDIVREM1:%[0-9]+]]:_ = G_UDIVREM [[AND]], [[AND1]]
    ; CHECK-NEXT: $r10 = COPY [[UDIVREM]](s32)
    ; CHECK-NEXT: $r11 = COPY [[UDIVREM1]](s32)
    ; CHECK-NEXT: RET implicit $r10, implicit $r11
    %0:_(s32) = COPY $r6
    %1:_(s16) = G_TRUNC %0
    %2:_(s16), %3:_(s16) = G_UDIVREM %1, %1
    %4:_(s32) = G_ANYEXT %2
    %5:_(s32) = G_ANYEXT %3
    $r10 = COPY %4:_(s32)
    $r11 = COPY %5:_(s32)
    RET implicit $r10, implicit $r11
...
---
name:              s32_sdiv
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s32_sdiv
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[SDIV:%[0-9]+]]:_(s32) = G_SDIV [[SDIV]], [[SDIV]]
    ; CHECK-NEXT: $r10 = COPY [[SDIV]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s32) = G_SDIV %1, %1
    $r10 = COPY %1:_(s32)
    RET implicit $r10
...
---
name:              s32_udiv
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s32_udiv
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[UDIV:%[0-9]+]]:_(s32) = G_UDIV [[UDIV]], [[UDIV]]
    ; CHECK-NEXT: $r10 = COPY [[UDIV]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s32) = G_UDIV %1, %1
    $r10 = COPY %1:_(s32)
    RET implicit $r10
...
---
name:              s32_srem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s32_srem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[SREM:%[0-9]+]]:_(s32) = G_SREM [[SREM]], [[SREM]]
    ; CHECK-NEXT: $r10 = COPY [[SREM]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s32) = G_SREM %1, %1
    $r10 = COPY %1:_(s32)
    RET implicit $r10
...
---
name:              s32_urem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s32_urem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[UREM:%[0-9]+]]:_(s32) = G_UREM [[UREM]], [[UREM]]
    ; CHECK-NEXT: $r10 = COPY [[UREM]](s32)
    ; CHECK-NEXT: RET implicit $r10
    %0:_(s32) = COPY $r6
    %1:_(s32) = G_UREM %1, %1
    $r10 = COPY %1:_(s32)
    RET implicit $r10
...
---
name:              s32_sdivrem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s32_sdivrem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[SDIVREM:%[0-9]+]]:_(s32), [[SDIVREM1:%[0-9]+]]:_ = G_SDIVREM [[SDIVREM]], [[SDIVREM]]
    ; CHECK-NEXT: $r10 = COPY [[SDIVREM]](s32)
    ; CHECK-NEXT: $r11 = COPY [[SDIVREM1]](s32)
    ; CHECK-NEXT: RET implicit $r10, implicit $r11
    %0:_(s32) = COPY $r6
    %1:_(s32), %2:_(s32) = G_SDIVREM %1, %1
    $r10 = COPY %1:_(s32)
    $r11 = COPY %2:_(s32)
    RET implicit $r10, implicit $r11
...
---
name:              s32_udivrem
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s32_udivrem
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[UDIVREM:%[0-9]+]]:_(s32), [[UDIVREM1:%[0-9]+]]:_ = G_UDIVREM [[UDIVREM]], [[UDIVREM]]
    ; CHECK-NEXT: $r10 = COPY [[UDIVREM]](s32)
    ; CHECK-NEXT: $r11 = COPY [[UDIVREM1]](s32)
    ; CHECK-NEXT: RET implicit $r10, implicit $r11
    %0:_(s32) = COPY $r6
    %1:_(s32), %2:_(s32) = G_UDIVREM %1, %1
    $r10 = COPY %1:_(s32)
    $r11 = COPY %2:_(s32)
    RET implicit $r10, implicit $r11
...
