# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -march=v810 -global-isel -run-pass=legalizer %s -o - | FileCheck %s
---
name:              s64_multiplication
tracksRegLiveness: true
body:              |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: s64_multiplication
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r6
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[COPY]](s32)
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s64) = G_MUL [[ANYEXT]], [[ANYEXT]]
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MUL]](s64)
    ; CHECK-NEXT: $r10 = COPY [[UV]](s32)
    ; CHECK-NEXT: $r11 = COPY [[UV1]](s32)
    ; CHECK-NEXT: RET implicit $r10, implicit $r11
    %0:_(s32) = COPY $r6
    %1:_(s64) = G_ANYEXT %0
    %2:_(s64) = G_MUL %1, %1
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %2(s64)
    $r10 = COPY %3:_(s32)
    $r11 = COPY %4:_(s32)
    RET implicit $r10, implicit $r11
