; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=v810 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o -| FileCheck %s

declare i32 @otherFunc(i32 %input)

define i32 @callingConv(i32 %input) {
  ; CHECK-LABEL: name: callingConv
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $r6
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r3, implicit $r3
  ; CHECK-NEXT:   $r6 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   CALL @otherFunc, csr, implicit-def $r31, implicit $r6, implicit-def $r10
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r3, implicit $r3
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[C]]
  ; CHECK-NEXT:   $r10 = COPY [[ADD]](s32)
  ; CHECK-NEXT:   RET implicit $r10
    %out = call i32 @otherFunc(i32 %input)
    %res = add i32 %out, 3
    ret i32 %res
}
