; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=v810 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o -| FileCheck %s

declare void @otherFunc()

define void @doesNotTailCallInInterrupt() "interrupt" {
  ; CHECK-LABEL: name: doesNotTailCallInInterrupt
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r3, implicit $r3
  ; CHECK-NEXT:   CALL @otherFunc, csr, implicit-def $r31
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r3, implicit $r3
  ; CHECK-NEXT:   RETI
    tail call void @otherFunc()
    ret void
}
