; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -march=v810 -verify-machineinstrs -global-isel | FileCheck %s

define i32 @test_atomic_load(ptr %ptr1) {
; CHECK-LABEL: test_atomic_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld.w 0[r6], r10
; CHECK-NEXT:    jmp [r31]
entry:
  %0 = load atomic i32, ptr %ptr1 acquire, align 4
  ret i32 %0
}

define void @test_atomic_store(ptr %ptr1) {
; CHECK-LABEL: test_atomic_store:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov 1, r7
; CHECK-NEXT:    st.w r7, 0[r6]
; CHECK-NEXT:    jmp [r31]
entry:
  store atomic i32 1, ptr %ptr1 release, align 4
  ret void
}
