; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=v810 | FileCheck %s

define i32 @truncFloatTest(float %a) {
; CHECK-LABEL: truncFloatTest:
; CHECK:       # %bb.0:
; CHECK-NEXT:    trnc.sw r6, r10
; CHECK-NEXT:    jmp [r31]
    %res = fptosi float %a to i32
    ret i32 %res
}
