; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -march=v810 | FileCheck %s

@var = external global i32

define void @preservesUsedRegisters() "interrupt" {
; CHECK-LABEL: preservesUsedRegisters:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -8, r3
; CHECK-NEXT:    st.w r6, 4[r3] # 4-byte Folded Spill
; CHECK-NEXT:    movhi hi(var), r0, r6
; CHECK-NEXT:    st.w r7, 0[r3] # 4-byte Folded Spill
; CHECK-NEXT:    movea lo(var), r6, r6
; CHECK-NEXT:    mov 10, r7
; CHECK-NEXT:    st.w r7, 0[r6]
; CHECK-NEXT:    ld.w 0[r3], r7 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 4[r3], r6 # 4-byte Folded Reload
; CHECK-NEXT:    add 8, r3
; CHECK-NEXT:    reti
    store i32 10, ptr @var, align 4
    ret void
}

declare void @otherFunc()

define void @preservesCSRsOnFunctionCall() "interrupt" {
; CHECK-LABEL: preservesCSRsOnFunctionCall:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movea -64, r3, r3
; CHECK-NEXT:    st.w r6, 60[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r7, 56[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r8, 52[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r9, 48[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r10, 44[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r11, 40[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r12, 36[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r13, 32[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r14, 28[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r15, 24[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r16, 20[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r17, 16[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r18, 12[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r19, 8[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r30, 4[r3] # 4-byte Folded Spill
; CHECK-NEXT:    st.w r31, 0[r3] # 4-byte Folded Spill
; CHECK-NEXT:    jal otherFunc
; CHECK-NEXT:    ld.w 0[r3], r31 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 4[r3], r30 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 8[r3], r19 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 12[r3], r18 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 16[r3], r17 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 20[r3], r16 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 24[r3], r15 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 28[r3], r14 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 32[r3], r13 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 36[r3], r12 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 40[r3], r11 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 44[r3], r10 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 48[r3], r9 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 52[r3], r8 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 56[r3], r7 # 4-byte Folded Reload
; CHECK-NEXT:    ld.w 60[r3], r6 # 4-byte Folded Reload
; CHECK-NEXT:    movea 64, r3, r3
; CHECK-NEXT:    reti
    tail call void @otherFunc()
    ret void
}
