; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=v810 | FileCheck %s

define half @guh(ptr %huh) {
; CHECK-LABEL: guh:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -4, r3
; CHECK-NEXT:    in.h 0[r6], r6
; CHECK-NEXT:    st.w r31, 0[r3] # 4-byte Folded Spill
; CHECK-NEXT:    jal __extendhfsf2
; CHECK-NEXT:    ld.w 0[r3], r31 # 4-byte Folded Reload
; CHECK-NEXT:    add 4, r3
; CHECK-NEXT:    jmp [r31]
    %res = load half, ptr %huh, align 4
    ret half %res
}

define i16 @convertToF16(float %a) {
; CHECK-LABEL: convertToF16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -4, r3
; CHECK-NEXT:    st.w r31, 0[r3] # 4-byte Folded Spill
; CHECK-NEXT:    jal __truncsfhf2
; CHECK-NEXT:    andi 65535, r10, r10
; CHECK-NEXT:    ld.w 0[r3], r31 # 4-byte Folded Reload
; CHECK-NEXT:    add 4, r3
; CHECK-NEXT:    jmp [r31]
    %res = call i16 @llvm.convert.to.fp16.f32(float %a)
    ret i16 %res
}

define float @convertFromF16(i16 %a) {
; CHECK-LABEL: convertFromF16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -4, r3
; CHECK-NEXT:    st.w r31, 0[r3] # 4-byte Folded Spill
; CHECK-NEXT:    jal __extendhfsf2
; CHECK-NEXT:    ld.w 0[r3], r31 # 4-byte Folded Reload
; CHECK-NEXT:    add 4, r3
; CHECK-NEXT:    jmp [r31]
    %res = call float @llvm.convert.from.fp16.f32(i16 %a)
    ret float %res
}
