; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -march=v810 | FileCheck %s

define void @doesNotMoveStack() {
; CHECK-LABEL: doesNotMoveStack:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jmp [r31]
    ret void
}

define void @movesStackALittleBit() {
; CHECK-LABEL: movesStackALittleBit:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -4, r3
; CHECK-NEXT:    add 4, r3
; CHECK-NEXT:    jmp [r31]
    %unused = alloca i32, align 4
    ret void
}

define void @movesStackMore() {
; CHECK-LABEL: movesStackMore:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -16, r3
; CHECK-NEXT:    movea 16, r3, r3
; CHECK-NEXT:    jmp [r31]
    %unused = alloca [ 4 x i32 ], align 4
    ret void
}

define void @movesStackEvenMore() {
; CHECK-LABEL: movesStackEvenMore:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movea -32, r3, r3
; CHECK-NEXT:    movea 32, r3, r3
; CHECK-NEXT:    jmp [r31]
    %unused = alloca [ 8 x i32 ], align 4
    ret void
}

define void @movesStackReallyFar() {
; CHECK-LABEL: movesStackReallyFar:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movea -32768, r3, r3
; CHECK-NEXT:    movea 32764, r3, r3
; CHECK-NEXT:    add 4, r3
; CHECK-NEXT:    jmp [r31]
    %unused = alloca [ 8192 x i32 ], align 4
    ret void
}
