; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -march=v810 -global-isel | FileCheck %s

declare i32 @otherFunc(i32 %input)

define i32 @tailCallThatClown(i32 %input) {
; CHECK-LABEL: tailCallThatClown:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jr otherFunc
    %res = tail call i32 @otherFunc(i32 %input)
    ret i32 %res
}

define i32 @tailCallWithStackAllocation(i32 %input) {
; CHECK-LABEL: tailCallWithStackAllocation:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add -4, r3
; CHECK-NEXT:    st.w r6, 0[r3]
; CHECK-NEXT:    add 4, r3
; CHECK-NEXT:    jr otherFunc
    %stack = alloca i32
    store i32 %input, ptr %stack, align 4
    %res = tail call i32 @otherFunc(i32 %input)
    ret i32 %res
}
